### ISSUE TITLE
Unexpected error when trying to reinstall the Integration

### ISSUE THREAD

**Issue by qbushome** [CharlesGillanders/homeassistant-alphaESS#29] opened 2022-08-29 06:33 UTC
I get an "unexpected error" when entering my credentials.
I think the last line in this errorlog says it all (?)

```
Logger: custom_components.alphaess.config_flow
Source: custom_components/alphaess/config_flow.py:44
Integration: Alpha ESS ([documentation](https://github.com/CharlesGillanders/homeassistant-alphaESS), [issues](https://github.com/CharlesGillanders/homeassistant-alphaESS/issues))
First occurred: 08:30:21 (1 occurrences)
Last logged: 08:30:21

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/alphaess/config_flow.py", line 66, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/alphaess/config_flow.py", line 44, in validate_input
    if not await client.authenticate(data["username"],data["password"]):
  File "/usr/local/lib/python3.10/site-packages/alphaess/alphaess.py", line 68, in authenticate
    self.tokencreatetime =  datetime.strptime(json_response["data"]["TokenCreateTime"],"%Y-%m-%d %H:%M:%S")
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022/8/29 6:30:21' does not match format '%Y-%m-%d %H:%M:%S'
```

**Comment by CharlesGillanders** [comment] 2022-08-29 08:40
I believe this is a duplicate of this issue https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/28

**Closed** 2022-08-29 08:40 UTC
