### ISSUE TITLE
Integrations stops working

### ISSUE THREAD

**Issue by dan-s-github** [CharlesGillanders/homeassistant-alphaESS#84] opened 2023-11-18 20:01 UTC
I installed new Integration on Friday afternoon and noticed that the Energy dashboard didn't show any values on Saturday.

After rebooting Home Assistant values came back.

Same thing happened today and I restarted Home Assistant again, waiting for Energy to show data

Startup log looks mostly fine

```
2023-11-19 08:00:10.909 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.al2002118050331_solar_to_battery from integration alphaess has state class total_increasing, but its state is negative. Triggered by state -0.3 with last_updated set to 2023-11-18T18:54:59.999999+00:00. Please create a bug report at https://github.com/CharlesGillanders/homeassistant-alphaESS/issues
2023-11-19 08:14:10.626 DEBUG (MainThread) [custom_components.alphaess] Finished fetching alphaess data in 3.099 seconds (success: True)
```

checking home-assistant.log.1 I found these issues

```
--
2023-11-18 17:33:23.268 ERROR (MainThread) [alphaess.alphaess] 502, message='Bad Gateway', url=URL('https://openapi.alphaess.com/api/getEssList')
2023-11-18 17:33:23.268 ERROR (MainThread) [alphaess.alphaess] 502, message='Bad Gateway', url=URL('https://openapi.alphaess.com/api/getEssList')
2023-11-18 17:33:23.269 ERROR (MainThread) [custom_components.alphaess] Error fetching alphaess data: 502, message='Bad Gateway', url=URL('https://openapi.alphaess.com/api/getEssList')
--
2023-11-19 00:00:51.156 ERROR (MainThread) [custom_components.alphaess] Unexpected error fetching alphaess data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 45, in _async_update_data
    _pv =  _onedateenergy.get("epv")
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-11-19 00:01:53.919 ERROR (MainThread) [custom_components.alphaess] Unexpected error fetching alphaess data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 45, in _async_update_data
    _pv =  _onedateenergy.get("epv")
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-11-19 00:02:56.932 ERROR (MainThread) [custom_components.alphaess] Unexpected error fetching alphaess data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 45, in _async_update_data
    _pv =  _onedateenergy.get("epv")
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-11-19 00:03:59.887 ERROR (MainThread) [custom_components.alphaess] Unexpected error fetching alphaess data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 45, in _async_update_data
    _pv =  _onedateenergy.get("epv")
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
--
2023-11-19 03:05:10.388 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.al2002118050331_solar_to_battery from integration alphaess has state class total_increasing, but its state is negative. Triggered by state -0.1 with last_updated set to 2023-11-18T14:04:01.891520+00:00. Please create a bug report at https://github.com/CharlesGillanders/homeassistant-alphaESS/issues
```

What I also noticed that solar production was not reset at midnight the day before (#75) affects also other totals but not all, somehow grid_to_battery was not reset yesterday but was today while others didn't reset at all.

![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/20974454/bcc21886-7448-4e7f-b1d9-5956d57cbe2c)

Service seem to work without issues

**Comment by milkmanrox** [comment] 2023-11-19 00:53
I was about to open an issue about the same thing. Everything with the new API works except the Energy tab reporting.

I am in GMT+10, and I think what I'm seeing is that the values start working by themselves by 10am.

**Comment by dan-s-github** [comment] 2023-11-19 01:12
Interesting observation and I had to check

I am in GMT+13 and can confirm that my values also started to show up at 1pm

**Comment by dan-s-github** [comment] 2023-11-19 04:06
three sensors were reset at midnight
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/20974454/f49ed033-c1d4-43d5-ae65-359ff2f7c69e)
and five at 1pm
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/20974454/ac65b1e4-93d9-4d8f-9162-181c4dfeb36a)
one sensor did not some other jump
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/20974454/79459efe-1db5-4b72-8a69-0856dcb99343)

will check if this will happen again tomorrow

**Comment by Poshy163** [comment] 2023-11-19 22:42
Dupe of #85, Seems to be a upstream issue, has been reported [here](https://github.com/alphaess-developer/alphacloud_open_api/issues/44)

**Comment by dan-s-github** [comment] 2023-11-20 03:26
last nights log entry around midnight
```
2023-11-20 00:00:07.646 ERROR (MainThread) [custom_components.alphaess] Unexpected error fetching alphaess data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alphaess/coordinator.py", line 45, in _async_update_data
_pv = _onedateenergy.get("epv")
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-11-20 00:01:10.619 ERROR (MainThread) [custom_components.alphaess] Unexpected error fetching alphaess data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alphaess/coordinator.py", line 45, in _async_update_data
_pv = _onedateenergy.get("epv")
^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
and two other entries after 1pm
```
2023-11-20 13:45:10.539 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.al2002118050331_solar_to_load from integration alphaess has state class total_increasing, but its state is not strictly increasing. Triggered by state 12.6 (12.8) with last_updated set to 2023-11-20T00:40:30.680668+00:00. Please create a bug report at https://github.com/CharlesGillanders/homeassistant-alphaESS/issues
2023-11-20 13:45:10.539 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.al2002118050331_total_load from integration alphaess has state class total_increasing, but its state is not strictly increasing. Triggered by state 12.6 (12.8) with last_updated set to 2023-11-20T00:40:30.680994+00:00. Please create a bug report at https://github.com/CharlesGillanders/homeassistant-alphaESS/issues
``` 
History panel views
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/20974454/4476fca9-d714-45b9-b3a1-00fd188e9c2f)
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/20974454/310c0f21-461a-454b-98d4-2e3297e8cae6)

**Comment by CharlesGillanders** [comment] 2023-11-29 14:10
Duplicat of Issue 85

**Closed by CharlesGillanders** 2023-11-29 14:10 UTC
