### ISSUE TITLE
verification code by postman

### ISSUE THREAD

**Issue by rk-code** [CharlesGillanders/homeassistant-alphaESS#155] opened 2024-12-19 18:02 UTC
Hello, I tried to get the verification code for registering my inverter on open.alphaess by using postman as descirbed in the documentation. To register directly at open.alphaess did not work, see #153.
Unfortunatly I get after sending getVerificationCode with my serial number and check code filled in corrcetly in the variables as a return
{
    "code": 6007,
    "msg": "Sign check error"
}
Do you have any idea whats going wrong ?

**Comment by Tumblehawk79** [comment] 2024-12-20 03:14
getting the same 6007 response from the postman send api

**Comment by CharlesGillanders** [comment] 2024-12-20 08:55
Looks like we need to further update the documentation.  As well as your serial number and check code you need to add your app id and app secret from the alphaESS developer portal into the variables for the collection.  Should be placeholders there already for those variables just as there was for serial and check code.

**Comment by Poshy163** [comment] 2024-12-21 05:01
Will do that now 👍🏻, once the updated read.md is merged, ill make a new hacs release and that should address all the current issues.

**Comment by Tumblehawk79** [comment] 2024-12-22 12:29
I think we may have a deeper issue with the Alpha Developer portal.
when signing up for Developer portal it no longer assigns/displays a AppID or Appsecret (the field seems to get a internal 500 error), so unable to try the verification process unless I'm missing something basic, I'm new to this.

when i view developer portal:
![Screenshot 2024-12-22 225729](https://github.com/user-attachments/assets/bfc29cb1-8d33-4694-bc83-8a7febba130b)

when i run the alpha developer portal verification get internal 500 error (known issue)
when i run postman api I get the 6007 sign check error (which i know is due to the missing ID and secret)  

so i don't think any real issue with your stuff, just seems their portal is broken.

**Comment by Poshy163** [comment] 2024-12-22 12:58
Yeah, wow. i mean you could try contacting alphaess support, and see what they say, but im not really sure who its responsible for the API/developer stuff anymore

**Comment by Tumblehawk79** [comment] 2024-12-22 13:15
I logged a service ticket under my device, will see where it goes.

**Comment by Tumblehawk79** [comment] 2024-12-23 01:42
# shellyn.chua
2024-12-23 01:13:25
Dear Customer, 
 
Thank you for bringing this issue to our attention. We have escalated your case to our API team for further investigation. Once the issue is resolved, we will contact you with an update.
 
We appreciate your patience and understanding. Should you have any further questions in the meantime, please feel free to reach out.
 
Kind regards,
Team Alpha ESS

**Comment by Tumblehawk79** [comment] 2024-12-23 02:20
seems to be fixed for me, my appID and appsecret appeared and was able to add my battery (the open.alphaess.com website seems to be working fine even did the verification code correctly, no 500 errors)

i did get about 8 verification messages all at once so suspect they had a backlog once they cleared the issue.  

HA install and configuration worked, can see data from battery in HA.

**Comment by Poshy163** [comment] 2024-12-23 09:39
Nice, i suspect this will fix most of the issues people have been happening with onboarding to the OpenAPI, glad to see they are fixing it pretty promptly after it being reported

**Closed by Poshy163** 2024-12-23 09:39 UTC
